<?php
/* +----------------------------------------------------------------------+
 * | SMS_Clickatell                                                       |
 * +----------------------------------------------------------------------+
 * | Copyright (c) 2002-2003 Jacques Marneweck                            |
 * +----------------------------------------------------------------------+
 * | This source file is subject to version 2.02 of the PHP license,      |
 * | that is bundled with this package in the file LICENSE, and is        |
 * | available at through the world-wide-web at                           |
 * | http://www.php.net/license/2_02.txt.                                 |
 * | If you did not receive a copy of the PHP license and are unable to   |
 * | obtain it through the world-wide-web, please send a note to          |
 * | license@php.net so we can mail you a copy immediately.               |
 * +----------------------------------------------------------------------+
 * | Authors: Jacques Marneweck <jacques@php.net>                         |
 * +----------------------------------------------------------------------+
 */

require_once 'PEAR.php';

/**
 * PHP Interface into Clickatell API
 *
 * @author	Jacques Marneweck <jacques@php.net>
 * @version	$Id: Clickatell.php,v 1.10 2004/01/30 11:09:55 jacques Exp $
 * @access	public
 * @package	SMS
 */

class SMS_Clickatell {
	/**
	 * Clickatell API Server
	 * @var string
	 */
	var $_api_server = "https://api.clickatell.com";

	/**
	 * Clickatell API Server Session ID
	 * @var string
	 */
	var $_session_id = null;

	/**
	 * Username from Clickatell used for authentication purposes
	 * @var string
	 */
	var $_username = null;

	/**
	 * Password for Clickatell Usernaem
	 * @var string
	 */
	var $_password = null;

	/**
	 * Clickatell API Server ID
	 * @var string
	 */
	var $_api_id = null;

	/**
	 * Temporary file resource id
	 * @var	resource
	 */
	var $_fp;

	/**
	 * Error codes generated by Clickatell Gateway
	 * @var array
	 */
	var $_errors = array (
		'001' => 'Authentication failed',
		'002' => 'Unknown username or password',
		'003' => 'Session ID expired',
		'004' => 'Account frozen',
		'005' => 'Missing session ID',
		'101' => 'Invalid or missing parameters',
		'102' => 'Invalid UDH. (User Data Header)',
		'103' => 'Unknown apismgid (API Message ID)',
		'104' => 'Unknown climsgid (Client Message ID)',
		'105' => 'Invalid Destination Address',
		'106' => 'Invalid Source Address',
		'107' => 'Empty message',
		'108' => 'Invalid or missing api_id',
		'109' => 'Missing message ID',
		'110' => 'Error with email message',
		'111' => 'Invalid Protocol',
		'112' => 'Invalid msg_type',
		'113' => 'Max message parts exceeded',
		'114' => 'Cannot route message',
		'115' => 'Message Expired',
		'116' => 'Invalid Unicode Data',
		'201' => 'Invalid batch ID',
		'202' => 'No batch template',
		'301' => 'No credit left',
		'302' => 'Max allowed credit'
	);

	/**
	 * Message status
	 *
	 * @var array
	 */
	var $_message_status = array (
		'001' => 'Message unknown',
		'002' => 'Message queued',
		'003' => 'Delivered',
		'004' => 'Received by recipient',
		'005' => 'Error with message',
		'006' => 'User cancelled message delivery',
		'007' => 'Error delivering message',
		'008' => 'OK',
		'009' => 'Routing error',
		'010' => 'Message expired',
		'011' => 'Message queued for later delivery',
		'012' => 'Out of credit'
	);

	var $_msg_types = array (
		'SMS_TEXT',
		'SMS_FLASH',
		'SMS_NOKIA_OLOGO',
		'SMS_NOKIA_GLOGO',
		'SMS_NOKIA_PICTURE',
		'SMS_NOKIA_RINGTONE',
		'SMS_NOKIA_RTTL',
		'SMS_NOKIA_CLEAN',
		'SMS_NOKIA_VCARD',
		'SMS_NOKIA_VCAL'
	);

	/**
	 * Authenticate to the Clickatell API Server.
	 *
	 * @return mixed true on sucess or PEAR_Error object
	 * @access public
	 * @since 1.1
	 */
	function auth () {
		$_url = $this->_api_server . "/http/auth";
		$_post_data = "user=" . $this->_username . "&password=" . $this->_password . "&api_id=" . $this->_api_id;
		$this->_fp = tmpfile();
		$_curl = curl_init();
		curl_setopt($_curl, CURLOPT_URL, $_url);
		curl_setopt($_curl, CURLOPT_TIMEOUT, 20);
		curl_setopt($_curl, CURLOPT_FILE, $this->_fp);
		curl_setopt($_curl, CURLOPT_POSTFIELDS, $_post_data);
		curl_setopt($_curl, CURLOPT_VERBOSE, 1);
		curl_setopt($_curl, CURLOPT_FAILONERROR, 1);
		curl_setopt($_curl, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($_curl, CURLOPT_COOKIEJAR, "/dev/null");

		$status = curl_exec($_curl);
		$response['http_code'] = curl_getinfo($_curl, CURLINFO_HTTP_CODE);

		if ($status) {
			$response['error'] = curl_error($_curl);
			$response['errno'] = curl_errno($_curl);
		}

		curl_close($_curl);

		rewind($this->_fp);

		$pairs = "";
		while ($str = fgets($this->_fp, 4096)) {
			$pairs .= $str;
		}
		fclose($this->_fp);

		$response['data'] = $pairs;
		unset($pairs);
		asort($response);
		$sess = split(":", $response['data']);

		$this->_session_id = trim($sess[1]);

		if ($sess[0] == "OK") {
			return (true);
		} else {
			return PEAR::raiseError($response['data']);
		}
	}

	/**
	 * Query balance of remaining SMS credits
	 *
	 * @access	public
	 * @since	1.9
	 */
	/**
	 * Get balance
	 *
	 * @since
	 */
	function getbalance () {
		$_url = $this->_api_server . "/http/getbalance";
		$_post_data = "session_id=" . $this->_session_id;

		$this->_fp = tmpfile();
		$_curl = curl_init();
		curl_setopt($_curl, CURLOPT_URL, $_url);
		curl_setopt($_curl, CURLOPT_TIMEOUT, 20);
		curl_setopt($_curl, CURLOPT_FILE, $this->_fp);
		curl_setopt($_curl, CURLOPT_POSTFIELDS, $_post_data);
		curl_setopt($_curl, CURLOPT_VERBOSE, 1);
		curl_setopt($_curl, CURLOPT_FAILONERROR, 1);
		curl_setopt($_curl, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($_curl, CURLOPT_COOKIEJAR, "/dev/null");

		$status = curl_exec($_curl);
		$response['http_code'] = curl_getinfo($_curl, CURLINFO_HTTP_CODE);

		if ($status) {
			$response['error'] = curl_error($_curl);
			$response['errno'] = curl_errno($_curl);
		}
		curl_close($_curl);

		rewind($this->_fp);

		$pairs = "";
		while ($str = fgets($this->_fp, 4096)) {
			$pairs .= $str;
		}
		fclose($this->_fp);

		$response['data'] = $pairs;
		asort($response);
		$send = split(":", $response['data']);

		if ($send[0] == "Credit") {
			return trim($send[1]);
		} else {
			return PEAR::raiseError($response['data']);
		}
	}

	/**
	 * Initilaise the Clicaktell SMS Class
	 *
	 * @access	public
	 * @since	1.9
	 */
	function init ($_params = array()) {
		if (is_array($_params)) {
			if (!isset($_params['user'])) {
				return PEAR::raiseError('Missing parameter user.');
			}

			if (!isset($_params['pass'])) {
				return PEAR::raiseError('Missing parameter pass.');
			}

			if (!isset($_params['api_id'])) {
				return PEAR::raiseError('Missing parameter api_id.');
			}

			$this->_username = $_params['user'];
			$this->_password = $_params['pass'];
			$this->_api_id = $_params['api_id'];
		} else {
			return PEAR::raiseError('You need to specify paramaters for authenticating to Clickatell.');
		}
	}

	/**
	 * Keep our session to the Clickatell API Server valid.
	 *
	 * @return mixed true on sucess or PEAR_Error object
	 * @access public
	 * @since 1.1
	 */
	function ping () {
		$_url = $this->_api_server . "/http/ping";
		$_post_data = "session_id=" . $this->_session_id;
		$this->_fp = tmpfile();
		$_curl = curl_init();
		curl_setopt($_curl, CURLOPT_URL, $_url);
		curl_setopt($_curl, CURLOPT_TIMEOUT, 20);
		curl_setopt($_curl, CURLOPT_FILE, $this->_fp);
		curl_setopt($_curl, CURLOPT_POSTFIELDS, $_post_data);
		curl_setopt($_curl, CURLOPT_VERBOSE, 1);
		curl_setopt($_curl, CURLOPT_FAILONERROR, 1);
		curl_setopt($_curl, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($_curl, CURLOPT_COOKIEJAR, "/dev/null");

		$status = curl_exec($_curl);
		$response['http_code'] = curl_getinfo($_curl, CURLINFO_HTTP_CODE);

		if ($status) {
			$response['error'] = curl_error($_curl);
			$response['errno'] = curl_errno($_curl);
		}
		curl_close($_curl);

		rewind($this->_fp);

		$pairs = "";
		while ($str = fgets($this->_fp, 4096)) {
			$pairs .= $str;
		}
		fclose($this->_fp);

		$response['data'] = $pairs;
		unset($pairs);
		asort($response);
		$sess = split(":", $response['data']);

		if ($sess[0] == "OK") {
			return (true);
		} else {
			return PEAR::raiseError($response['data']);
		}
	}

	/**
	 * Query message status
	 *
	 * @param string spimsgid generated by Clickatell API
	 *
	 * @return string message status or PEAR_Error object 
	 * @access public
	 * @since 1.5
	 */

	function querymsg ($apimsgid) {
		$_url = $this->_api_server . "/http/querymsg";
		$_post_data = "session_id=" . $this->_session_id . "&apimsgid=" . $apimsgid;
		$this->_fp = tmpfile();
		$_curl = curl_init();
		curl_setopt($_curl, CURLOPT_URL, $_url);
		curl_setopt($_curl, CURLOPT_TIMEOUT, 20);
		curl_setopt($_curl, CURLOPT_FILE, $this->_fp);
		curl_setopt($_curl, CURLOPT_POSTFIELDS, $_post_data);
		curl_setopt($_curl, CURLOPT_VERBOSE, 1);
		curl_setopt($_curl, CURLOPT_FAILONERROR, 1);
		curl_setopt($_curl, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($_curl, CURLOPT_COOKIEJAR, "/dev/null");

		$status = curl_exec($_curl);
		$response['http_code'] = curl_getinfo($_curl, CURLINFO_HTTP_CODE);

		if ($status) {
			$response['error'] = curl_error($_curl);
			$response['errno'] = curl_errno($_curl);
		}
		curl_close($_curl);

		rewind($this->_fp);

		$pairs = "";
		while ($str = fgets($this->_fp, 4096)) {
			$pairs .= $str;
		}
		fclose($this->_fp);

		$response['data'] = $pairs;
		unset($pairs);
		asort($response);
		$status = split(" ", $response['data']);

		if ($status[0] == "ID:") {
			return (trim($status[3]));
		} else {
			return PEAR::raiseError($response['data']);
		}
	}

	/**
	 * Send an SMS Message via the Clickatell API Server
	 *
	 * @param array database result set
	 *
	 * @return mixed true on sucess or PEAR_Error object
	 * @access public
	 * @since 1.2
	 */
	function sendmsg ($_msg) {
		$_url = $this->_api_server . "/http/sendmsg";
		$_post_data = "session_id=" . $this->_session_id . "&to=" . $_msg['to'] . "&text=" . urlencode ($_msg['text']) . "&callback=3&deliv_ack=1&from=" . $_msg['from'] . "&climsgid=" . $_msg['climsgid'];

		if (!in_array($_msg['msg_type'], $this->_msg_types)) {
			return PEAR::raiseError("Invalid message type. Message ID is " . $_msg['id']);
		}

		if ($_msg['msg_type'] != "SMS_TEXT") {
			$_post_data .= $_post_data . "&msg_type=" . $_msg['msg_type'];
		}

		$this->_fp = tmpfile();
		$_curl = curl_init();
		curl_setopt($_curl, CURLOPT_URL, $_url);
		curl_setopt($_curl, CURLOPT_TIMEOUT, 20);
		curl_setopt($_curl, CURLOPT_FILE, $this->_fp);
		curl_setopt($_curl, CURLOPT_POSTFIELDS, $_post_data);
		curl_setopt($_curl, CURLOPT_VERBOSE, 1);
		curl_setopt($_curl, CURLOPT_FAILONERROR, 1);
		curl_setopt($_curl, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($_curl, CURLOPT_COOKIEJAR, "/dev/null");

		$status = curl_exec($_curl);
		$response['http_code'] = curl_getinfo($_curl, CURLINFO_HTTP_CODE);

		if ($status) {
			$response['error'] = curl_error($_curl);
			$response['errno'] = curl_errno($_curl);
		}
		curl_close($_curl);

		rewind($this->_fp);

		$pairs = "";
		while ($str = fgets($this->_fp, 4096)) {
			$pairs .= $str;
		}
		fclose($this->_fp);

		$response['data'] = $pairs;
		asort($response);
		$send = split(":", $response['data']);

		if ($send[0] == "ID") {
			return array ("1", trim($send[1]));
		} else {
			return PEAR::raiseError($response['data']);
		}
	}
}

/* vim: set noet ts=4 sw=4 ft=php: : */
